version: 1

#
# Pleroma settings
#
# You can enter any config in here that you want.
# Pleroma-Docker will try to translate it into elixir for you.
#
# For example:
#
# :foo:
#   Bar.Baz:
#     x: true
#
# becomes `config :foo, Bar.Baz, x: true`.
#
# It is assumed that all config keys that have to be passed through to
# pleroma must start with an atom on the first layer (eg :pleroma).
#

app:
  # The loglevel to use in pleroma.
  :logger:
    level: info

  :pleroma:
    Pleroma.Repo:
      # Credentials for your database.
      # You should leave this as-is if you want to use the managed db container.
      hostname: db
      username: pleroma
      password: pleroma
      database: pleroma
      pool_size: 16

    Pleroma.Web.Endpoint:
      # Location where your instance will be reachable.
      url:
        <T>: Array
        scheme: https
        host: coolsite.moe
        port: 443

      # Base for your secret keys.
      # Better make this random.
      secret_key_base: asdf0815

    Pleroma.Upload:
      # Where to store your uploads.
      # You should probably leave this as-is.
      # /uploads will be mounted into ::docker::datadir.
      uploads: /uploads

      # Remove metadata from uploads?
      strip_exif: true

    :chat:
      # Enable chat functionality?
      enabled: true

    :media_proxy:
      # Enable the proxy?
      enabled: true

      # Emit a 302 to the original resource when uncached?
      redirect_on_failure: true

      # Where your proxy is reachable
      base_url: https://media.coolsite.moe

    :instance:
      # The name of your instance.
      name: super cool stuff club

      # Short description of your instance
      description: we do super cool stuff in super cool stuff club

      # The admin's email address.
      email: admin@coolsite.moe

      # How many chars a notice may have at max.
      limit: 4096

      # May new members sign up?
      registrations_open: true

      # Allow connections to other instances?
      # (Turn this off for testing)
      federating: true

      # The rewrite policies / quarantines to enable.
      # This is a powerful feature which should be used with care.
      # Take a look at https://git.pleroma.social/pleroma/pleroma/wikis/Message%20rewrite%20facility%20configuration%20(how%20to%20block%20instances).
      # Then uncomment only the things you really need

      # quarantined_instances:
      #   - badguys.moe

      # rewrite_policy:
      #   - Pleroma.Web.ActivityPub.MRF.SimplePolicy

      # :mrf_simple:
      #   media_removal:
      #     - illegalporn.biz
      #   media_nsfw:
      #     - porn.biz
      #     - porn.business
      #   reject:
      #     - spam.com
      #   federated_timeline_removal:
      #     - spam.university
